name: Release

on:
  push:
    branches:
      - master
      - develop

permissions:
  actions: write
  security-events: write
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run tests
        run: uv run python run_tests.py
      - name: Commitizen release
        uses: commitizen-tools/commitizen-action@0.24.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: true
          push: true

  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Release
        uses: release-drafter/release-drafter@v5
        with:
          version: ${{ env.REVISION }}
          tag: ${{ env.REVISION }}
          name: ${{ env.REVISION }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}